"""create automation jobs table

Revision ID: 24460433c6d4
Revises: ef7da960fc32
Create Date: 2026-07-12 23:21:54.695259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24460433c6d4'
down_revision: Union[str, Sequence[str], None] = 'ef7da960fc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='queued', nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_jobs_celery_task_id'), 'automation_jobs', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_automation_jobs_id'), 'automation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_automation_jobs_job_type'), 'automation_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_automation_jobs_project_id'), 'automation_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_automation_jobs_status'), 'automation_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_jobs_status'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_project_id'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_job_type'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_id'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_celery_task_id'), table_name='automation_jobs')
    op.drop_table('automation_jobs')
    # ### end Alembic commands ###
