"""create health checks and diagnosis reports

Revision ID: ef7da960fc32
Revises: 52e52019c58f
Create Date: 2026-07-12 20:42:57.161580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7da960fc32'
down_revision: Union[str, Sequence[str], None] = '52e52019c58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('baseline_dataset_id', sa.Integer(), nullable=False),
    sa.Column('prediction_batch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('drift', sa.JSON(), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('missing_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_batch_id'], ['prediction_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_checks_baseline_dataset_id'), 'health_checks', ['baseline_dataset_id'], unique=False)
    op.create_index(op.f('ix_health_checks_id'), 'health_checks', ['id'], unique=False)
    op.create_index(op.f('ix_health_checks_model_version_id'), 'health_checks', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_health_checks_prediction_batch_id'), 'health_checks', ['prediction_batch_id'], unique=False)
    op.create_index(op.f('ix_health_checks_project_id'), 'health_checks', ['project_id'], unique=False)
    op.create_table('diagnosis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_check_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('retraining_recommended', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['health_check_id'], ['health_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_reports_health_check_id'), 'diagnosis_reports', ['health_check_id'], unique=True)
    op.create_index(op.f('ix_diagnosis_reports_id'), 'diagnosis_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_reports_id'), table_name='diagnosis_reports')
    op.drop_index(op.f('ix_diagnosis_reports_health_check_id'), table_name='diagnosis_reports')
    op.drop_table('diagnosis_reports')
    op.drop_index(op.f('ix_health_checks_project_id'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_prediction_batch_id'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_model_version_id'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_id'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_baseline_dataset_id'), table_name='health_checks')
    op.drop_table('health_checks')
    # ### end Alembic commands ###
